PickupPup/Pickup-Pup

Assets/Scenes/Main.unity

Edited Main scene to match UI on Sam's slides.
- Added placeholders for Time, Food, and Money icons
- Adjusted layout of Top Panel and its contents for flexibility
- Renamed objects for clarity
- Added Outside Group for dogs outside w/ names, thumbnails, and timers
- Added Home Group for dogs inside w/ label and thumbnails
- Added Adopt Button (does nothing)

Main Screen UI

---

Assets/Prefabs/Pickup Pup/Game.prefab
Assets/Prefabs/Pickup Pup/Game.prefab.meta
Assets/Scenes/Main.unity
Assets/Scenes/Start.unity
Assets/Scripts/Audio/AudioController.cs
Assets/Scripts/Core/Templates/MonoBehaviourExtended.cs
Assets/Scripts/Core/Templates/SingletonController.cs
Assets/Scripts/Event/EventController.cs
Assets/Scripts/Event/EventController.cs.meta
Assets/Scripts/UI/Core/UIEventListener.cs

- Added PPEvent enum
- Refactored EventController to use singleton implementation instead of static implementation (fixed a garbage collection bug we discovered with GemSpinner)
- Made the Subscription and Un-subscription calls into wrapped methods

Refactor of event system

---

Assets/Prefabs/Pickup Pup/DogAdoptProfile.prefab
Assets/Prefabs/Pickup Pup/DogAdoptionSlot.prefab
Assets/Prefabs/Pickup Pup/DogProfile.prefab
Assets/Prefabs/Pickup Pup/DogProfile.prefab.meta
Assets/Prefabs/Pickup Pup/ShelterUI.prefab
Assets/Scenes/Home.unity
Assets/Scenes/LivingRoom.unity
Assets/Scenes/Shelter.unity
Assets/Scenes/Yard.unity
Assets/Scripts/UI/Pickup Pup/DogProfile/DogAdoptProfile.cs
Assets/Scripts/UI/Pickup Pup/DogProfile/DogProfile.cs

**Prefabs**
- DogAdoptProfile, DogProfile: updated UI to match wireframes
**Scenes**
- Added DogProfile to LivingRoom, Yard, and Home scenes
- Added newest DogAdoptProfile to Shelter scene
- Deleted missing reference on DogAdoptionSlot UI buttons (Adopt() is handled in PPShelterUIController now)
**Scripts**
- DogAdoptProfile: combined deactivating Rehome and Collar buttons into one line, added regions, cost text turns red when the player can't afford it
- DogProfile: now sets description text components from description field game objects, deactivates extra description fields (such as when a dog is not special)

Updated DogProfile UI

---

Assets/Prefabs/PickupPup/DogBrowser.prefab
Assets/Prefabs/PickupPup/MainMenuUI.prefab
Assets/Prefabs/PickupPup/Settings/SettingsPopup.prefab
Assets/Scenes/Dev/MainMenu.unity
Assets/Scenes/Dev/MainMenu.unity.meta
Assets/Scenes/LivingRoom.unity
Assets/Scenes/Shelter.unity
Assets/Scenes/Shop.unity
Assets/Scenes/Yard.unity
Assets/Scripts/Controller/PickupPup/PPSceneController.cs
Assets/Scripts/UI/Core/UIElement.cs
Assets/Scripts/UI/PickupPup/Core/PPUIController.cs
Assets/Scripts/UI/PickupPup/MainMenu/PPMainMenuUIController.cs
Assets/Scripts/UI/PickupPup/NavPanel/NavigationPanel.cs
Assets/Scripts/UI/PickupPup/ShopScreen/PPShopUIController.cs

**Prefabs**
- DogBrowser, SettingsPopup: changed to be deactivated by default, increased sorting order 0 -> 3
- MainMenuUI: changed preferred width
**Scenes**
- MainMenu: moved to Dev folder since it no longer needs to be its own scene
- LivingRoom, Shelter, Shop, Yard: added MainMenuUI, DogBrowser, and SettingsPopup prefabs, set reference in NavigationPanel
**Scripts**
- PPUIController: removed method to LoadMainMenu
- PPMainMenuUIController: now inherits from PPUIElement and not PPUIController
- NavigationPanel: now shows the MainMenuUI popup instead of loading the MainMenu scene

Implemented Main Menu, Settings Menu, and Dog Browser into each scene

---

Assets/Scripts/Data/PickupPup/DogDescriptor.cs
Assets/Scripts/Data/PickupPup/PPDataController.cs
Assets/Scripts/Event/EventController.cs

**Scripts**
- Added adopt event to `EventController`
- Check for `string PPGlobal.ADOPT` with a `PPData.DogActionStr` event handler

Adding global adopt event

---

Assets/Scripts/UI/PickupPup/DogSlot/DogOutsideSlot.cs
Assets/Scripts/UI/PickupPup/DogSlot/DogSlot.cs
Assets/Scripts/World/PickupPup/Dog.cs

**Scripts**
- DogOutsideSlot, Dog: fixed spelling error
- DogSlot: removed condition that would auto-eject dogs

Fixed NullRefs and Disappearing Dogs

---

Assets/Scripts/Data/PickupPup/DogDatabase.cs
Assets/Scripts/Data/PickupPup/PPDataController.cs
Assets/Scripts/Factories/DogFactory.cs
Assets/Scripts/UI/PickupPup/DogBrowser/DogBrowser.cs
Assets/Scripts/Util/ListUtil.cs

**Scripts**
- DogDatabase: added method to return its DogDescriptors within a specified range as a list
- PPDataController: moved event call to after the Adopt method completes
- DogFactory: added method to convert a list of DogDescriptors to a list of Dogs
- DogBrowser: listens to global adopt event and updates itself with the new dog, changed dogCollection to a list, changed several methods that referenced dogCollection to return a list instead of an array
- ListUtil: added InRange and CopyRange methods

Dog Browser updates on Adopt Event

---

Assets/Prefabs/PickupPup/LivingRoom/LivingRoomUI.prefab
Assets/Prefabs/PickupPup/PopupPrompt.prefab
Assets/Prefabs/PickupPup/PopupPrompt.prefab.meta
Assets/Prefabs/PickupPup/Shelter/ShelterUI.prefab
Assets/Prefabs/PickupPup/Yard/YardUI.prefab
Assets/Resources/JSON/Languages.json
Assets/Scenes/Dev/Popup_Dev.unity
Assets/Scenes/Dev/Popup_Dev.unity.meta
Assets/Scenes/LivingRoom.unity
Assets/Scripts/Controller/PickupPup/PPGameController.cs
Assets/Scripts/UI/PickupPup/Core/PPUIController.cs
Assets/Scripts/UI/PickupPup/Livingroom/PPLivingRoomUIController.cs
Assets/Scripts/UI/PickupPup/PopupPrompts.meta
Assets/Scripts/UI/PickupPup/PopupPrompts/PopupPrompt.cs
Assets/Scripts/UI/PickupPup/PopupPrompts/PopupPrompt.cs.meta
Assets/Scripts/UI/PickupPup/ShelterScreen/PPShelterUIController.cs
Assets/Scripts/UI/PickupPup/YardScreen/PPYardUIController.cs
Assets/Scripts/Util/ListUtil.cs
Assets/Scripts/Util/PlayerPrefsUtil.cs
ProjectSettings/GraphicsSettings.asset

**Prefabs**
- LivingRoomUI, YardUI, ShelterUI: added reference to PopupPrompt prefab
- PopupPrompt: new prefab
**Resources**
- Languages: added keys for ShelterPrompt & ScoutingPrompt (from change in spreadsheet)
**Scenes**
- Shelter: I'm not sure any of these changes were intentional
**Scripts**
- PPGameController: added accessor for LanguageDatabase
- PPUIController: added two variables and a show method for the popup prompt
- PPLivingRoomUIController, PPShelterUIController, PPYardUIController: added an override method to only show their popup prompt if it hasn't been shown before
- PopupPrompt: new script for control the popup prompt
- PlayerPrefsUtil: added static variables & accessors for shownShelterPrompt & shownScoutingPrompt

TEMPORARY: Added Popup Prompts for Shelter & Scouting

---

Assets/Resources/Sprites/dogsprites1.png.meta
Assets/Resources/Sprites/sheltericon.png.meta

i notice it has THIS note, but not the original one I made about adding the sheltericon and dogsprite1 files to begin with... not sure where they are anymore

still trying to add the metas for the sheltericon and dog sprites

---

README.md

Add Credits to README.md

---

README.md

Added Liam's name and website URL to the README.

Liam credits

---

Assets/Prefabs/PickupPup/Core/UI/DogProfile.prefab
Assets/Prefabs/PickupPup/Shelter/DogShelterProfile.prefab
Assets/Scenes/Dev/DogProfile_Dev.unity
Assets/Scripts/UI/PickupPup/DogProfile/DogProfile.cs
ProjectSettings/ProjectSettings.asset

**Prefabs**
- Re-added refs to dog profiles 
**Scripts**
- Re-serialized the description field so it can be set in inspector

Fixing dog descriptions not showing up

---

Assets/Scripts/Controller/PickupPup/PPGameController.cs
Assets/Scripts/UI/PickupPup/DogSlot/DogCollarSlot.cs

**Scripts**
- Moved SFX event call from `PPGameController` to `DogCollarSlot`

Moving the dog return event into the DogCollarSlot event handler

---

Assets/Scripts/Core/TemplateClasses/MonoBehaviourExtended.cs
Assets/Scripts/Data/PickupPup/Currency/CurrencyData.cs
Assets/Scripts/Data/PickupPup/Currency/ICurrencySystem.cs
Assets/Scripts/Data/PickupPup/PPData.cs
Assets/Scripts/Data/PickupPup/PPDataController.cs
Assets/Scripts/UI/Core/Button/ToggleableUIButton.cs
Assets/Scripts/UI/PickupPup/Currency/PriceTag.cs
Assets/Scripts/UI/PickupPup/DogBrowser/DogBrowser.cs
Assets/Scripts/UI/PickupPup/DogProfile/DogProfileButtonController.cs
Assets/Scripts/UI/PickupPup/DogSlot/DogSlot.cs
Assets/Scripts/UI/PickupPup/Livingroom/RedeemDisplay.cs
Assets/Scripts/UI/PickupPup/ShopScreen/PPShopUIController.cs
Assets/Scripts/UI/PickupPup/ShopScreen/ShopItemSlot.cs

Fixed compile time warnings across many scripts. Functionally nothing should have changed

Removing compile time warnings

---

Assets/Scripts/UI/PickupPup/DogBrowser/DogBrowser.cs
Assets/Scripts/UI/PickupPup/DogBrowser/DogBrowserButtonController.cs

**Asana Task**
https://app.asana.com/0/290156159252311/276176353237103
**Scripts**
- `DogBrowserButtonController`: added logic for changing button display dynamically
- `DogBrowser`: added call to `DogBrowserButtonController` to raise a flag to refresh

Fixing BUG - Dog Browser New Pages

---

Assets/Prefabs/PickupPup/Shelter/DogShelterProfile.prefab
Assets/Prefabs/PickupPup/Shelter/DogShelterProfile.prefab.meta
Assets/Prefabs/PickupPup/Shelter/DogShelterSlot.prefab
Assets/Prefabs/PickupPup/Shelter/DogShelterSlot.prefab.meta
Assets/Prefabs/PickupPup/Shelter/ShelterUI.prefab
Assets/Prefabs/PickupPup/Shop/ShopUI.prefab
Assets/Scenes/Shelter.unity
Assets/Scripts/UI/PickupPup/DogWorld/DogWorldSlot.cs

**Prefabs**
- DogShelterProfile, DogShelterSlot: changed background color
- ShelterUI, Shop UI: added new backgrounds
**Scenes**
- Shelter: rerouted references between ShelterUI and DogShelterProfile
**Scripts**
- Set transition on Dog World Slot's button component to "None"

Changed Button on Dog World Slot & Added 2 Backgrounds

---

Assets/Prefabs/PickupPup/Core/UI/DogBrowser.prefab
Assets/Scripts/Data/PickupPup/Currency/CurrencyData.cs
Assets/Scripts/FeedingSystem/DogFoodBowl.cs
Assets/Scripts/UI/PickupPup/DogBrowser/DogBrowserButtonController.cs

**Prefabs**
- DogBrowser: removed rehome button gameobject
**Scripts**
- CurrencyData: made it so that canAfford() will always return false if amount is <= 0 (previously you could fill the dog bowl with 0 dog food as long as you didn't adopt any dogs yet).
- DogBrowserButtonController: removed rehome button variable and its refs

Removed Rehome Button & Fixed Dog Feeding Bug

---

Assets/Prefabs/PickupPup/Home/HomeUI.prefab

**Prefabs**
- HomeUI: Moved full dog sprites up so that none of them were behind the collar slots, moved yard dog bowl down so that it wasn't over the pond.

Rearranged home gameobjects (full dogs + bowl)

---

Assets/Prefabs/PickupPup/Home/HomeUI.prefab

**Prefabs**
- HomeUI: added aspect ratio fitters to Living Room and Yard backgrounds

Fixed Background Aspect Ratio

---

Assets/Scripts/DogAI/DogAI.cs
Assets/Scripts/UI/PickupPup/DogProfile/DogProfileButtonController.cs
Assets/Scripts/UI/PickupPup/DogProfile/DogShelterProfile.cs
Assets/Scripts/UI/PickupPup/DogSlot/DogCollarSlot.cs
Assets/Scripts/UI/PickupPup/ShelterScreen/PPShelterUIController.cs
Assets/Scripts/World/PickupPup/Dog.cs

Dogs should only play the bark SFX associated with its size.
**Scripts**
- DogAI: extracted local variable, added call to new Bark method in Dog
- DogProfileButtonController: corrected styles, added a new instance accessor for SelectedDog
- DogShelterProfile: added new instance accessor for DisplayedDog
- DogCollarSlot, PPShelterUIController: use new Bark method in Dog
- Dog: added bark method

Fixed Layered Barks (plus minor refactoring)

---

Assets/Prefabs/PickupPup/Tools.meta
Assets/Prefabs/PickupPup/Tools/DogSprites.meta
Assets/Prefabs/PickupPup/Tools/DogSprites/DogSpriteDisplay.prefab
Assets/Prefabs/PickupPup/Tools/DogSprites/DogSpriteDisplay.prefab.meta
Assets/Prefabs/PickupPup/Tools/DogSprites/DogSpriteTool.prefab
Assets/Prefabs/PickupPup/Tools/DogSprites/DogSpriteTool.prefab.meta
Assets/Scenes/Tools.meta
Assets/Scenes/Tools/DogSprite_Tool.unity
Assets/Scenes/Tools/DogSprite_Tool.unity.meta
Assets/Scripts/Data/PickupPup/Globals/PPGlobal.cs
Assets/Scripts/Tools/DogSpriteDisplayTool.cs
Assets/Scripts/Tools/DogSpriteDisplayTool.cs.meta
Assets/Scripts/Tools/DogSpriteTool.cs
Assets/Scripts/Tools/DogSpriteTool.cs.meta

https://app.asana.com/0/235862522711549/319039773705914
**Scenes**
- Added DogSprite_Tool scene
**Prefabs**
- Added prefabs for the sprite tool (as a UICanvas)
- And displaying an individual dog w/ name and 2 sprites
**Scripts**
- Added scripts for displaying all dogs sprites inside a scroll rect

Adding dog sprite tool

---

Assets/Prefabs/PickupPup/Home/Dog.prefab
Assets/Prefabs/PickupPup/Home/Dog.prefab.meta
Assets/Prefabs/PickupPup/Home/HomeUI.prefab
Assets/Scenes/Dev/DogWorld_Dev.unity
Assets/Scripts/UI/PickupPup/DogSlot/DogSlot.cs
Assets/Scripts/UI/PickupPup/DogWorld/DogWorldSlot.cs
Assets/Scripts/UI/PickupPup/DogWorld/NameTag.cs
Assets/Scripts/UI/PickupPup/DogWorld/NameTag.cs.meta
Assets/Scripts/UI/PickupPup/HomeScreen/PPHomeUIController.cs
Assets/Scripts/UI/Testing/DogWorldTest.cs
Assets/Scripts/World/PickupPup/DogAI/DogAI.cs

**Prefabs**
- Dog: new dog prefab with name tag
- HomeUI: uses copies of new dog prefab
**Scenes**
- DogWorld_Dev: testing for dog name tags
**Scripts**
- DogWorldSlot: added ref to name tag, added subscription methods, moved around setting of some refs
- NameTag: new script
- PPHomeUIController: subscribes to all the name tags so it can show the dog profile
- DogWorldTest: fleshed out test script to accommodate new functionality
- DogAI: cut the wander radius in half (should limit the dogs from climbing walls)

Name Tags & Limit Dog Wander Radius

---

Assets/Scripts/UI/PickupPup/DogProfile/DogProfile.cs
Assets/Scripts/UI/PickupPup/DogProfile/DogShelterProfile.cs

Fixed bug where you couldn't adopt a dog, click next on the dog shelter profile, and adopt the next one.
**Scripts**
- DogProfile: removed unused libraries, added dog variable, added protected accessor for dog's info, cleaned up styles, set dog variable in SetProfile
- DogShelterProfile: removed dog variable (in superclass now)

Fixed Shelter Profile Adoption Bug

---

Assets/Prefabs/PickupPup/Core/UI/NavMenuUI.prefab
Assets/Prefabs/PickupPup/Core/UI/SettingsMenu.prefab
Assets/Scripts/UI/PickupPup/MainMenu/MainMenu.cs
Assets/Scripts/UI/PickupPup/SettingsMenu/SettingsMenu.cs
Assets/Scripts/Util/SettingsUtil.cs

**Prefabs**
- NavMenuUI: removed game objects related to the multi-dropdown
- SettingsMenu: removed option to change the nav menu type
**Scripts**
- MainMenu: removed variables and functions related to old menu option, added serialized ref to settings menu
- SettingsMenu, SettingsUtil: removed functionality for changing nav menu options

Removed multi-dropdown & Added serialized ref to Settings Menu

---

Assets/Resources/JSON/Gifts.json
Assets/Scripts/Controller/PickupPup/PPGiftController.cs
Assets/Scripts/Data/Core/RandomBuffer.cs
Assets/Scripts/Data/PickupPup/Currency/DogVoucherData.cs
Assets/Scripts/Data/PickupPup/Currency/GiftEventData.cs
Assets/Scripts/Data/PickupPup/GiftDatabase.cs
Assets/Scripts/Event/EventController.cs
Assets/Scripts/Exceptions/GiftEventNotAvailableException.cs
Assets/Scripts/Exceptions/GiftEventNotAvailableException.cs.meta
Assets/Scripts/Factories/CurrencyFactory.cs
Assets/Scripts/UI/PickupPup/DogWorld/DogWorld.cs
Assets/Scripts/UI/PickupPup/DogWorld/DogWorldSlot.cs
Assets/Scripts/World/PickupPup/DogAI/DogAI.cs

https://app.asana.com/0/319039773705935/327071586346992
**JSON**
- Added field to `giftEvents` JSON object to limit number of simultaneous occurrences of an event
**Scripts**
- Adding dog to `DogWorld` when the dog is adopted from redeeming a dog from scouting
- Ensuring only one instance of Tub-Tub can exist at once
- If there's a case where the game will return a second Tub-Tub instance, it defaults to returning a random amount of one of the base currencies instead (food or coins)

Fine-tune Special Gifts

---

Assets/Scripts/UI/PickupPup/DogWorld/DogWorld.cs

**Scripts**
- DogWorld: changed dogSlots variable back to class variable, changed parameter of chooseDogs method to int, checked if the newly selected dog is the same as the last one before deselecting it

Fixed error in DogWorld & Checked for selection of same dog

---

Assets/Prefabs/PickupPup/Tools/DogSprites/DogSpriteDisplay.prefab
Assets/Prefabs/PickupPup/Tools/DogSprites/DogSpriteTool.prefab
Assets/Resources/JSON/GameData.json
Assets/Resources/JSON/Souvenirs.json
Assets/Scenes/Tools/DogSprite_Tool.unity
Assets/Scripts/Tools/DogSpriteDisplayTool.cs

**Prefabs**
- Changed Dog Sprite Tool to also display souvenirs
**JSON**
- Updated Souvenirs.json
- Updated GameData.json to include all souvenirs with implemented sprites so far

Updating souvenir refs and expanding dog sprite tool to check souvenirs

---

Assets/Scripts/UI/PickupPup/DogWorld/DogWorld.cs

**Scripts**
- `DogWorld`: Check whether dogSlot is null

Fixing null ref on deselect

---

Assets/Plugins/UnityPurchasing/Editor.meta

**Meta Files**
- Unity updated value in `Assets/Plugins/UnityPurchasing/Editor.meta` file
(this will hopefully stop the popup which keeps prompting me to update the plugin)

Updating Unity IAP plugin

---

Assets/Resources/Sprites/tub-tub.png.meta

https://app.asana.com/0/330037316655382/324309549248663
**Sprites**
- Adjusted the crop in the .meta file for the Tub-Tub sprite

Fixing cropping of Tub-Tub sprites

---

Assets/Prefabs/PickupPup/Core/GameLogic/Game.prefab
Assets/Scenes/Home.unity
Assets/Scripts/Data/Core/GameSave.cs
Assets/Scripts/Data/Core/Global.cs
Assets/Scripts/Data/Core/SerializableData.cs
Assets/Scripts/Data/PickupPup/DogDescriptor.cs
Assets/Scripts/Data/PickupPup/Globals/PPGlobal.cs
Assets/Scripts/Data/PickupPup/PPDataController.cs
Assets/Scripts/Data/PickupPup/PPGameSave.cs
Assets/Scripts/Notifications.meta
Assets/Scripts/Notifications/INotificationInterchange.cs
Assets/Scripts/Notifications/INotificationInterchange.cs.meta
Assets/Scripts/Notifications/NotificationController.cs
Assets/Scripts/Notifications/NotificationController.cs.meta
Assets/Scripts/Notifications/PPNotification.cs
Assets/Scripts/Notifications/PPNotification.cs.meta
Assets/Scripts/Notifications/iOSNotificationInterchange.cs
Assets/Scripts/Notifications/iOSNotificationInterchange.cs.meta

https://app.asana.com/0/330037316655382/237071087658956
**Scripts**
- Created `NotificationController`, `INotificationInterchange`, and `iOSNotificationInterchange`
- Added support to `PPGameSave` and `PPDataController` to create a unique save path for each game save (which other scripts can use)
- Added calls in`DogDescriptor` to schedule notifications (and cancel them if the dog returns from scouting while the game is open)
**Prefabs**
- Added `NotificationController` to the `Game` prefab
**Scenes**
- Fixed `Game` prefab ref in the `Home` scene

Adding Support for iOS Local Notifications when Dogs Return from Scouting
